/**
 * Author: Karmil Asgarally - INTELLEKTRA © 2026
 * @nexus/accounts public exports
 */
import { allAssignableRoleNames, listRoleCatalog, registerRoleCatalog } from './catalog.js'
import {
  disable2fa,
  enable2fa,
  forgotPassword,
  generate2faQr,
  has2fa,
  loginWithFacebook,
  loginWithGoogle,
  loginWithPassword,
  resetPassword,
} from './authClient.js'
import {
  getRoleAssignmentCollection,
  getUsersCollection,
  authOptions,
  insertUser,
  removeUser,
  rolesForUser,
  selfRegister,
  setOrg,
  setPassword,
  setRoles,
  setSuspended,
  subscribeDirectory,
  subscribeRoleAssignments,
  subscribeUsers,
  updateUser,
} from './helpers.js'
import { getMeteorApis, registerWithMeteor } from './register.js'

export {
  DEFAULT_SELF_REGISTER_ROLES,
  METHOD_AUTH_OPTIONS,
  METHOD_ROLES_SET,
  METHOD_SELF_REGISTER,
  METHOD_USERS_INSERT,
  METHOD_USERS_REMOVE,
  METHOD_USERS_SET_ORG,
  METHOD_USERS_SET_PASSWORD,
  METHOD_USERS_SET_SUSPENDED,
  METHOD_USERS_UPDATE,
  PLATFORM_CATALOG_KEY,
  PUBLICATION_DIRECTORY,
  PUBLICATION_ROLE_ASSIGNMENTS,
  PUBLICATION_USERS,
  USER_ROLE,
  USERS_COLLECTION,
} from './constants.js'

export {
  allAssignableRoleNames,
  authOptions,
  disable2fa,
  enable2fa,
  forgotPassword,
  generate2faQr,
  getMeteorApis,
  getRoleAssignmentCollection,
  getUsersCollection,
  has2fa,
  insertUser,
  listRoleCatalog,
  loginWithFacebook,
  loginWithGoogle,
  loginWithPassword,
  registerRoleCatalog,
  registerWithMeteor,
  removeUser,
  resetPassword,
  selfRegister,
  rolesForUser,
  setOrg,
  setPassword,
  setRoles,
  setSuspended,
  subscribeDirectory,
  subscribeRoleAssignments,
  subscribeUsers,
  updateUser,
}

export const Accounts = {
  registerWithMeteor,
  registerRoleCatalog,
  listRoleCatalog,
  allAssignableRoleNames,
  subscribeUsers,
  subscribeDirectory,
  subscribeRoleAssignments,
  authOptions,
  selfRegister,
  loginWithPassword,
  forgotPassword,
  resetPassword,
  loginWithGoogle,
  loginWithFacebook,
  generate2faQr,
  enable2fa,
  disable2fa,
  has2fa,
  insertUser,
  updateUser,
  removeUser,
  setPassword,
  setRoles,
  setSuspended,
  setOrg,
  rolesForUser,
  get users() {
    return getUsersCollection()
  },
  get roleAssignment() {
    return getRoleAssignmentCollection()
  },
}
